# Generated by Django 4.1.1 on 2022-09-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=60)),
                ('weight', models.FloatField()),
                ('heigth', models.IntegerField(verbose_name='heigth(cm)')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Futbolchi',
                'verbose_name_plural': 'Futbolchilar',
            },
        ),
    ]
